### ISSUE TITLE
Memory issue with files required inside a loop

### ISSUE THREAD

**Issue by Revak** [giggsey/Locale#17]
Hey,
we were using the` \libphonenumber\geocoding\PhoneNumberOfflineGeocoder::getDescriptionForNumber` method inside a customer data export so it was called on every iteration to parse each customer's phone number. With the OPCache file_cache enabled, we were getting memory exhaustion errors (over 1Gb of memory used). 

This was caused each time by one of the requires from the `\Giggsey\Locale\Locale::getDisplayRegion` method lines 63 and 91. Replacing these `require` with `require_once` in the `\Giggsey\Locale\Locale` class resolved the issue.

**Comment by giggsey** [comment]
Are you sure require_once fixes it?

Replacing line 63

```diff
-         $regionList = require $dataDir . '_list.php';
+         $regionList = require_once $dataDir . '_list.php';
```

causes the tests to fail, because require_once returns true on the subsequent executions

**Comment by Revak** [comment]
I tried again and yes just replacing both `require` with `require_once` fixes it with no error.

In our project we realized we didn't need more than the formatted phone number so we resolved the issue by not calling `getDescriptionForNumber` inside our export.
