### ISSUE TITLE
Unsupported Locales

### ISSUE THREAD

**Issue by martin-neumann-gurus** [giggsey/Locale#28]
I see that you support a number of different english locales, but en-us is missing. The same way there is no pt-br. Those are quite important locales and I wonder for what reason they are not supported.

**Comment by giggsey** [comment]
The base locale (en) has the default values, and the country codes underneath have overrides from that base locale.

For example, the base [en](https://github.com/giggsey/Locale/blob/master/data/en.php#L134) has a value for `'KN' => 'St. Kitts & Nevis'`. [en-GB](https://github.com/giggsey/Locale/blob/master/data/en-gb.php#L13) overrides that and has a different value `St Kitts & Nevis` (a missing full stop).
