### ISSUE TITLE
update package versions please

### ISSUE THREAD

**Issue by gdinko** [giggsey/Locale#31]
Hi , if possible can you update package versions , for exampla : symfony/filesystem 

thanks

**Comment by giggsey** [comment]
The symfony components are only used as dev dependencies. The only dependency for other projects wanting to use this one is PHP itself.

**Comment by gdinko** [comment]
yes i see , but we have laravel 10 , with pest and pest drift plugin does not want to install . :(
if possible plese update .
Thanks .

**Comment by giggsey** [comment]
If you are using this package in your composer.json, the dev dependencies here won't impact your project at all.

I believe you can use the composer why-not command to see what is actually blocking your upgrades.
